tasks:
  - before: sudo apt update && sudo apt install mariadb-server -y && sudo service mariadb start
    command: sudo service mariadb start
vscode:
  extensions:
    - cweijan.vscode-mysql-client2
